name: 'Push Javadocs into Branch'
description: 'It will not generate javadocs itself, you need to use maven to create javadoc'
author: 'Eric Lam'

inputs:
  branch:
    description: 'the branch that push into'
    required: false
    default: 'gh-pages'
  javadocs:
    description: 'the javadocs directory name'
    required: true
  use-maven:
    description: 'if true, it will run mvn clean first'
    required: false
    default: false

runs:
  using: "composite"
  steps: 
    - run: ls -la
      shell: bash
    - run: sh javadoc.sh ${{ inputs.branch }} ${{ inputs.javadocs }} ${{ inputs.use-maven }}
      shell: bash
