# This is a basic workflow to help you get started with Actions

name: Debug my actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # use my own checkout
      - uses: actions/checkout@v2
      - name: 'create fake javadocs directory'
        run: |
          mkdir docs && cd docs
          echo "<p> hello world! </p>" > index.html
      # debug my own actions
      - uses: eric2788/push-javadoc-branch@main
        with:
          javadocs: docs
          branch: my-pages
          use-maven: false
